### ISSUE TITLE
Is it backed up for me regularly?

### ISSUE THREAD

**Issue by AGDholo** [sikalabs/tergum#20]
I want to use the tergum to backup my postgres data to the AWS s3,
Do I set an additional timed task?

**Comment by kaplan-michael** [comment]
Hey @AGDholo,  It is done one time(on each run) so if you want to have it regularly backup, you'd have to run tergum on some kind of schedule(cron, etc.)
If you are on kubernetes you can use our helm chart https://github.com/sikalabs/charts/tree/master/charts/tergum-cronjob(you'll maybe need to use a newer image in values)

**Comment by kaplan-michael** [comment]
I'm closing this as answered above, if needed, we can reopen.
